### ISSUE TITLE
Additional options

### ISSUE THREAD

**Issue by TheDuckCow** [leomoon-studios/leomoon-textcounter#1]
A work in progress, I have been adding additional options to the counter code. Screen shot sample:

![screen shot 2017-02-05 at 11 43 05 pm](https://cloud.githubusercontent.com/assets/2958461/22634975/03afabde-ebfd-11e6-86bf-3869d10840a9.png)

**Added options for:**

- Commas for large numbers
- Option to use "international numbers", swapping commas for points, and points for commas
- Option to use "abbreviations", upper or lowercase, such as M for million, B for billion. (note to self: need to make this work further with decimals instead of truncating as it does now)

**Comment by leomoon** [comment]
Awesome dude. When you're done, I'll add you to the list of developers.

**Comment by leomoon** [comment]
I've added your name to programmers section of the README.md file.

Thanks for your contributions. :)
