### ISSUE TITLE
If number is animated to translate, no movement occurs while performing animation render

### ISSUE THREAD

**Issue by HardRooster** [leomoon-studios/leomoon-textcounter#6]
Example file: [https://drive.google.com/open?id=1NDRFnyUwtAYNTjT0qlE7C-2zN58_XIbP](https://drive.google.com/open?id=1NDRFnyUwtAYNTjT0qlE7C-2zN58_XIbP)

The animation works fine in the viewport, and it'll work if doing a single frame (F12) render, but if you try to render the animation (Ctrl-F12) the numbers will always be located on the frame the playhead is placed on.

**Comment by leomoon** [comment]
This looks like to be a Blender bug:
https://developer.blender.org/T71908

**Comment by leomoon** [comment]
Closing this as this is a duplicate: https://github.com/leomoon-studios/leomoon-textcounter/issues/5
