### ISSUE TITLE
Addon doesn't work on Blender 2.93 Beta

### ISSUE THREAD

**Issue by Oxervision** [leomoon-studios/leomoon-textcounter#8]
Hi, the first, thanks for the addon!!

The addon works fine on Blender 2.83 LTS & 2.92 but on 2.93 Beta it appears an error message in Console when I run Blender:

```
rna_uiItemR: property not found: TextCounter_Props.ifAnimated
/Users/User/Library/Application Support/Blender/SCRIPTS/addons/blender-text-counter.py:177
Python: Traceback (most recent call last):
  File "/Users/User/Library/Application Support/Blender/SCRIPTS/addons/blender-text-counter.py", line 183, in draw
    layout.enabled = props.ifAnimated
TypeError: bpy_struct: item.attr = val: UILayout.enabled expected True/False or 0/1, not _PropertyDeferred

```
Can you help me to fix the issue?
Thanks in advance!!

**macOS 10.13.6 & Blender 2.93 Beta**

**Comment by leomoon** [comment]
Hi,

This is a Blender bug. You can install the addon by following the steps below:

- Delete the 2.93 folder at this location:
  C:\Users\LeoMoon\AppData\Roaming\Blender Foundation\Blender
- Open blender and in the Blender welcome popup, click "Save New Settings".
- Close Blender.
- Open Blender and install the addon.

**Comment by leomoon** [comment]
Hi,

We will fix all of our addons once the stable version is out. Blender alpha and beta versions change too much. :P

**Comment by Oxervision** [comment]
Ok, thanks for the info!!

**Comment by TheDuckCow** [comment]
FYI this is a fairly simple fix, I've implemented it in some other repos already, and is backwards compatible:
https://github.com/CGCookie/blender-addon-updater/pull/74/commits/cde48f2054a9896f88eb2d1ba75046187769aabd

I see you are already using the same `make_annotations` function, this update would just add in the deferred property type if the blender version is detected to be 2.93+, and works still on 3.0. May not solve all issues for you, but likely the biggest.

**Comment by leomoon** [comment]
Thanks @TheDuckCow , I'll update it very soon. :)

**Comment by leomoon** [comment]
Please try the new version 1.3.6.
